export interface Product {
  id: string
  name: string
  category: string
  price: number
  subscriptionPrice: number | null
  image: string
  overview: string
  benefits: string[]
  useCases: string[]
  disclaimer: string
  reviews: {
    rating: number
    count: number
    featured: string
  }
  purity?: number
  storage?: string
  description?: string
  molecularWeight?: string
  casNumber?: string
  sequence?: string
  researchApplications?: string[]
}

export const categories = [
  "All",
  "Weight Loss",
  "Skin & Beauty",
  "Recovery & Healing",
  "Muscle Growth",
  "Longevity",
  "Cognitive",
  "Bioregulators",
  "Hormones & Sexual Health",
]

// Helper function to calculate subscription price (15% discount)
const getSubscriptionPrice = (price: number) => {
  return Math.round(price * 0.85 * 100) / 100
}

export const products: Product[] = [
  // ============================================
  // WEIGHT LOSS CATEGORY
  // ============================================
  
  // Retatrutide
  {
    id: "retatrutide-10mg",
    name: "Retatrutide 10mg",
    category: "Weight Loss",
    price: 125.00,
    subscriptionPrice: getSubscriptionPrice(125.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Retatrutide is a novel triple agonist targeting GIP, GLP-1, and glucagon receptors. It's under investigation for treating obesity, diabetes, and metabolic conditions.",
    benefits: ["Accelerates weight loss", "Improves metabolic markers", "Enhances insulin sensitivity", "Potential NAFLD treatment"],
    useCases: ["Advanced metabolic research", "Multi-receptor studies", "Novel therapy research"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 67, featured: "Cutting-edge for multi-receptor research." },
  },
  {
    id: "retatrutide-20mg",
    name: "Retatrutide 20mg",
    category: "Weight Loss",
    price: 183.00,
    subscriptionPrice: getSubscriptionPrice(183.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Retatrutide is a novel triple agonist targeting GIP, GLP-1, and glucagon receptors. It's under investigation for treating obesity, diabetes, and metabolic conditions.",
    benefits: ["Accelerates weight loss", "Improves metabolic markers", "Enhances insulin sensitivity", "Potential NAFLD treatment"],
    useCases: ["Advanced metabolic research", "Multi-receptor studies", "Novel therapy research"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 54, featured: "Excellent for advanced research protocols." },
  },
  {
    id: "retatrutide-40mg",
    name: "Retatrutide 40mg",
    category: "Weight Loss",
    price: 373.00,
    subscriptionPrice: getSubscriptionPrice(373.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Retatrutide is a novel triple agonist targeting GIP, GLP-1, and glucagon receptors. It's under investigation for treating obesity, diabetes, and metabolic conditions.",
    benefits: ["Accelerates weight loss", "Improves metabolic markers", "Enhances insulin sensitivity", "Potential NAFLD treatment"],
    useCases: ["Institutional research", "Premium studies", "Advanced dosing protocols"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.9, count: 32, featured: "Premium quality for institutional research." },
  },
  {
    id: "retatrutide-60mg",
    name: "Retatrutide 60mg",
    category: "Weight Loss",
    price: 523.00,
    subscriptionPrice: getSubscriptionPrice(523.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Retatrutide is a novel triple agonist targeting GIP, GLP-1, and glucagon receptors. It's under investigation for treating obesity, diabetes, and metabolic conditions.",
    benefits: ["Accelerates weight loss", "Improves metabolic markers", "Enhances insulin sensitivity", "Potential NAFLD treatment"],
    useCases: ["Bulk research", "Institutional applications", "Large-scale studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.9, count: 18, featured: "Outstanding value for bulk research." },
  },

  // Semaglutide
  {
    id: "semaglutide-10mg",
    name: "Semaglutide 10mg",
    category: "Weight Loss",
    price: 56.00,
    subscriptionPrice: getSubscriptionPrice(56.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Semaglutide is a GLP-1 receptor agonist used for managing type 2 diabetes and chronic weight management. It enhances insulin secretion and suppresses appetite.",
    benefits: ["Appetite suppression", "Substantial weight reduction", "Improved HbA1c levels", "Cardiovascular risk reduction"],
    useCases: ["GLP-1 research", "Appetite studies", "Metabolic syndrome research"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 189, featured: "Reliable for GLP-1 research." },
  },
  {
    id: "semaglutide-20mg",
    name: "Semaglutide 20mg",
    category: "Weight Loss",
    price: 86.00,
    subscriptionPrice: getSubscriptionPrice(86.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Semaglutide is a GLP-1 receptor agonist used for managing type 2 diabetes and chronic weight management. It enhances insulin secretion and suppresses appetite.",
    benefits: ["Appetite suppression", "Substantial weight reduction", "Improved HbA1c levels", "Cardiovascular risk reduction"],
    useCases: ["Advanced GLP-1 research", "High-dose studies", "Extended protocols"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 98, featured: "Excellent for advanced GLP-1 research." },
  },

  // Tirzepatide
  {
    id: "tirzepatide-15mg",
    name: "Tirzepatide 15mg",
    category: "Weight Loss",
    price: 184.00,
    subscriptionPrice: getSubscriptionPrice(184.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Tirzepatide is a dual GIP and GLP-1 receptor agonist developed to treat type 2 diabetes and support weight loss.",
    benefits: ["Glycemic control", "Weight loss", "Insulin sensitivity", "Cardiovascular risk reduction"],
    useCases: ["Comprehensive diabetes research", "Extended metabolic studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 89, featured: "Excellent mid-range option for metabolic research." },
  },
  {
    id: "tirzepatide-30mg",
    name: "Tirzepatide 30mg",
    category: "Weight Loss",
    price: 253.00,
    subscriptionPrice: getSubscriptionPrice(253.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Tirzepatide is a dual GIP and GLP-1 receptor agonist developed to treat type 2 diabetes and support weight loss.",
    benefits: ["Glycemic control", "Weight loss", "Insulin sensitivity", "Cardiovascular risk reduction"],
    useCases: ["Premium diabetes research", "Maximum dose studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.9, count: 45, featured: "Premium option for advanced research." },
  },
  {
    id: "tirzepatide-60mg",
    name: "Tirzepatide 60mg",
    category: "Weight Loss",
    price: 278.00,
    subscriptionPrice: getSubscriptionPrice(278.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Tirzepatide is a dual GIP and GLP-1 receptor agonist developed to treat type 2 diabetes and support weight loss.",
    benefits: ["Glycemic control", "Weight loss", "Insulin sensitivity", "Cardiovascular risk reduction"],
    useCases: ["Institutional research", "Bulk study applications"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.9, count: 23, featured: "Exceptional value for large-scale research." },
  },

  // Other Weight Loss
  {
    id: "adipotide-fttp-5mg",
    name: "Adipotide/FTTP 5mg",
    category: "Weight Loss",
    price: 240.00,
    subscriptionPrice: getSubscriptionPrice(240.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Adipotide is an experimental peptidomimetic that targets blood vessels feeding white adipose tissue, causing fat cell apoptosis.",
    benefits: ["Targets adipose tissue", "Promotes fat cell apoptosis", "Experimental fat reduction"],
    useCases: ["Adipose tissue research", "Fat reduction studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 34, featured: "Cutting-edge adipose tissue research compound." },
  },
  {
    id: "aod9604-5mg",
    name: "AOD9604 5mg",
    category: "Weight Loss",
    price: 143.00,
    subscriptionPrice: getSubscriptionPrice(143.00),
    image: "/images/precision-peptides-vial.png",
    overview: "AOD9604 is a modified fragment of human growth hormone that stimulates lipolysis and inhibits lipogenesis.",
    benefits: ["Stimulates fat breakdown", "Inhibits fat formation", "No effect on blood sugar"],
    useCases: ["Fat metabolism research", "Body composition studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 78, featured: "Effective for fat metabolism research." },
  },
  {
    id: "aod9604-10mg",
    name: "AOD9604 10mg",
    category: "Weight Loss",
    price: 257.00,
    subscriptionPrice: getSubscriptionPrice(257.00),
    image: "/images/precision-peptides-vial.png",
    overview: "AOD9604 is a modified fragment of human growth hormone that stimulates lipolysis and inhibits lipogenesis.",
    benefits: ["Stimulates fat breakdown", "Inhibits fat formation", "No effect on blood sugar"],
    useCases: ["Extended fat metabolism research", "Bulk studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 45, featured: "Great value for extended research." },
  },
  {
    id: "cagrilintide-10mg",
    name: "Cagrilintide 10mg",
    category: "Weight Loss",
    price: 265.00,
    subscriptionPrice: getSubscriptionPrice(265.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Cagrilintide is a long-acting amylin analog being developed for obesity treatment, working to reduce appetite and food intake.",
    benefits: ["Appetite reduction", "Weight loss support", "Metabolic improvement"],
    useCases: ["Amylin pathway research", "Appetite studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 28, featured: "Novel approach to appetite research." },
  },
  {
    id: "cagrisema-5mg",
    name: "Cagrisema (2.5mg+2.5mg) 5mg",
    category: "Weight Loss",
    price: 125.00,
    subscriptionPrice: getSubscriptionPrice(125.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Cagrisema combines cagrilintide and semaglutide for synergistic weight loss effects targeting multiple pathways.",
    benefits: ["Dual mechanism action", "Enhanced weight loss", "Metabolic benefits"],
    useCases: ["Combination therapy research", "Synergistic studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 42, featured: "Powerful combination for metabolic research." },
  },
  {
    id: "mazdutide-10mg",
    name: "Mazdutide 10mg",
    category: "Weight Loss",
    price: 173.00,
    subscriptionPrice: getSubscriptionPrice(173.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Mazdutide is a dual GLP-1/glucagon receptor agonist being developed for obesity and type 2 diabetes treatment.",
    benefits: ["Dual receptor activation", "Weight reduction", "Glycemic control"],
    useCases: ["Dual agonist research", "Metabolic studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 35, featured: "Promising dual agonist compound." },
  },
  {
    id: "mazdutide-10mg-premium",
    name: "Mazdutide 10mg (Premium)",
    category: "Weight Loss",
    price: 291.00,
    subscriptionPrice: getSubscriptionPrice(291.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Premium grade Mazdutide dual GLP-1/glucagon receptor agonist for advanced research applications.",
    benefits: ["Dual receptor activation", "Weight reduction", "Glycemic control"],
    useCases: ["Advanced dual agonist research", "Premium studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 22, featured: "Premium quality for advanced research." },
  },
  {
    id: "survodutide-10mg",
    name: "Survodutide 10mg",
    category: "Weight Loss",
    price: 379.00,
    subscriptionPrice: getSubscriptionPrice(379.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Survodutide is a dual GLP-1/glucagon receptor agonist showing promise for obesity and metabolic liver disease.",
    benefits: ["Weight loss", "Liver fat reduction", "Metabolic improvement"],
    useCases: ["NAFLD research", "Metabolic studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 19, featured: "Exciting compound for liver research." },
  },
  {
    id: "5-amino-1mq-5mg",
    name: "5-AMINO-1MQ 5mg",
    category: "Weight Loss",
    price: 57.00,
    subscriptionPrice: getSubscriptionPrice(57.00),
    image: "/images/precision-peptides-vial.png",
    overview: "5-AMINO-1MQ is a small molecule that blocks NNMT enzyme, potentially increasing NAD+ and promoting fat metabolism.",
    benefits: ["NNMT inhibition", "NAD+ increase", "Fat metabolism support"],
    useCases: ["Metabolic enzyme research", "Fat loss studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 56, featured: "Innovative approach to metabolic research." },
  },
  {
    id: "5-amino-1mq-10mg",
    name: "5-AMINO-1MQ 10mg",
    category: "Weight Loss",
    price: 78.00,
    subscriptionPrice: getSubscriptionPrice(78.00),
    image: "/images/precision-peptides-vial.png",
    overview: "5-AMINO-1MQ is a small molecule that blocks NNMT enzyme, potentially increasing NAD+ and promoting fat metabolism.",
    benefits: ["NNMT inhibition", "NAD+ increase", "Fat metabolism support"],
    useCases: ["Extended metabolic research", "Higher dose studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 38, featured: "Good value for extended research." },
  },
  {
    id: "5-amino-1mq-oral",
    name: "5-AMINO-1MQ Oral 50mcg x 60pcs",
    category: "Weight Loss",
    price: 94.00,
    subscriptionPrice: getSubscriptionPrice(94.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Oral formulation of 5-AMINO-1MQ for convenient research applications.",
    benefits: ["Oral delivery", "NNMT inhibition", "Convenient dosing"],
    useCases: ["Oral bioavailability studies", "Convenient research"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 29, featured: "Convenient oral research format." },
  },
  {
    id: "tesofensine-oral",
    name: "Tesofensine 500mcg x 100pcs",
    category: "Weight Loss",
    price: 76.00,
    subscriptionPrice: getSubscriptionPrice(76.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Tesofensine is a serotonin-noradrenaline-dopamine reuptake inhibitor studied for weight loss.",
    benefits: ["Triple reuptake inhibition", "Appetite suppression", "Weight loss support"],
    useCases: ["Neurotransmitter research", "Appetite studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.4, count: 33, featured: "Interesting neurotransmitter compound." },
  },
  {
    id: "l-carnitine-5000mg",
    name: "L-Carnitine 5000mg",
    category: "Weight Loss",
    price: 90.00,
    subscriptionPrice: getSubscriptionPrice(90.00),
    image: "/images/precision-peptides-vial.png",
    overview: "L-Carnitine plays a crucial role in energy metabolism by transporting fatty acids into mitochondria.",
    benefits: ["Fat transport", "Energy metabolism", "Exercise performance"],
    useCases: ["Metabolic research", "Energy studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 67, featured: "Essential for energy metabolism research." },
  },
  {
    id: "lipo-c-10ml",
    name: "Lipo-C 10ml",
    category: "Weight Loss",
    price: 104.00,
    subscriptionPrice: getSubscriptionPrice(104.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Lipo-C is a lipotropic blend containing compounds like methionine, inositol, choline, and B12 for fat metabolism.",
    benefits: ["Boosts metabolism", "Liver detoxification", "Energy enhancement"],
    useCases: ["Metabolism research", "Fat studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 43, featured: "Good for metabolism research." },
  },
  {
    id: "mic-lipo-c-b12-10mg",
    name: "MIC (Lipo C with B12) 10mg",
    category: "Weight Loss",
    price: 157.00,
    subscriptionPrice: getSubscriptionPrice(157.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Enhanced lipotropic blend with added B12 for improved metabolic support.",
    benefits: ["Enhanced metabolism", "B12 benefits", "Energy support"],
    useCases: ["Enhanced metabolic research", "Combination studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 31, featured: "Enhanced formula for better results." },
  },

  // ============================================
  // SKIN & BEAUTY CATEGORY
  // ============================================
  {
    id: "ghk-cu-50mg",
    name: "GHK-Cu 50mg",
    category: "Skin & Beauty",
    price: 41.00,
    subscriptionPrice: getSubscriptionPrice(41.00),
    image: "/images/precision-peptides-vial.png",
    overview: "GHK-Cu is a copper peptide complex with strong regenerative, anti-inflammatory, and anti-aging properties.",
    benefits: ["Wound healing", "Collagen stimulation", "Anti-inflammatory", "Skin texture improvement"],
    useCases: ["Dermatological research", "Collagen studies", "Anti-aging research"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 167, featured: "Outstanding for collagen research." },
  },
  {
    id: "ghk-cu-100mg",
    name: "GHK-Cu 100mg",
    category: "Skin & Beauty",
    price: 60.00,
    subscriptionPrice: getSubscriptionPrice(60.00),
    image: "/images/precision-peptides-vial.png",
    overview: "GHK-Cu is a copper peptide complex with strong regenerative, anti-inflammatory, and anti-aging properties.",
    benefits: ["Wound healing", "Collagen stimulation", "Anti-inflammatory", "Skin texture improvement"],
    useCases: ["Extended dermatological research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 98, featured: "Great value for extended research." },
  },
  {
    id: "ahk-cu-100mg",
    name: "AHK-Cu 100mg",
    category: "Skin & Beauty",
    price: 90.00,
    subscriptionPrice: getSubscriptionPrice(90.00),
    image: "/images/precision-peptides-vial.png",
    overview: "AHK-Cu is a copper peptide variant studied for hair growth stimulation and skin regeneration.",
    benefits: ["Hair growth support", "Skin regeneration", "Copper peptide benefits"],
    useCases: ["Hair follicle research", "Skin studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 45, featured: "Promising for hair research." },
  },
  {
    id: "snap8-10mg",
    name: "Snap8 10mg",
    category: "Skin & Beauty",
    price: 56.00,
    subscriptionPrice: getSubscriptionPrice(56.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Snap8 is an octapeptide that reduces wrinkle depth by inhibiting muscle contraction at the neuromuscular junction.",
    benefits: ["Wrinkle reduction", "Muscle relaxation", "Anti-aging"],
    useCases: ["Cosmetic research", "Anti-wrinkle studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 52, featured: "Effective for cosmetic research." },
  },
  {
    id: "melanotan-i-10mg",
    name: "Melanotan I 10mg",
    category: "Skin & Beauty",
    price: 69.00,
    subscriptionPrice: getSubscriptionPrice(69.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Melanotan I is a synthetic analog of alpha-MSH that induces melanin production for tanning.",
    benefits: ["Melanin production", "Photoprotection", "Tanning support"],
    useCases: ["Melanogenesis research", "Skin pigmentation studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 89, featured: "Excellent for melanogenesis research." },
  },
  {
    id: "melanotan-ii-10mg",
    name: "Melanotan II 10mg",
    category: "Skin & Beauty",
    price: 61.00,
    subscriptionPrice: getSubscriptionPrice(61.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Melanotan II is a more potent derivative offering both tanning and libido-enhancing effects.",
    benefits: ["Tanning", "Libido enhancement", "Fat loss support"],
    useCases: ["Melanin research", "Receptor studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 134, featured: "Excellent for melanogenesis research." },
  },
  {
    id: "glow-70mg",
    name: "GLOW (BPC 157 10mg + GHK-Cu 50mg + TB500 10mg) 70mg",
    category: "Skin & Beauty",
    price: 262.00,
    subscriptionPrice: getSubscriptionPrice(262.00),
    image: "/images/precision-peptides-vial.png",
    overview: "GLOW is a proprietary blend combining three powerful peptides for skin health and regeneration.",
    benefits: ["Collagen production", "Skin elasticity", "Tissue repair", "Anti-aging"],
    useCases: ["Skin regeneration research", "Anti-aging studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.9, count: 143, featured: "Outstanding combination for skin research." },
  },
  {
    id: "glow-plus-80mg",
    name: "BPC 10mg + GHK-Cu 50mg + TB500 10mg + KPV 10mg (80mg)",
    category: "Skin & Beauty",
    price: 305.00,
    subscriptionPrice: getSubscriptionPrice(305.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Enhanced GLOW formula with added KPV for additional anti-inflammatory benefits.",
    benefits: ["Enhanced regeneration", "Anti-inflammatory", "Comprehensive skin support"],
    useCases: ["Advanced skin research", "Combination studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.9, count: 67, featured: "Premium formula for comprehensive research." },
  },

  // ============================================
  // RECOVERY & HEALING CATEGORY
  // ============================================
  {
    id: "bpc157-oral-500mcg",
    name: "BPC157 Oral 500mcg x 100pcs",
    category: "Recovery & Healing",
    price: 78.00,
    subscriptionPrice: getSubscriptionPrice(78.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Oral formulation of BPC-157 for convenient gut healing and systemic research.",
    benefits: ["Gut healing", "Oral convenience", "Systemic effects"],
    useCases: ["Oral bioavailability studies", "GI research"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 87, featured: "Convenient oral format for gut research." },
  },
  {
    id: "bpc157-5mg",
    name: "BPC 157 5mg",
    category: "Recovery & Healing",
    price: 56.00,
    subscriptionPrice: getSubscriptionPrice(56.00),
    image: "/images/precision-peptides-vial.png",
    overview: "BPC-157 is a synthetic peptide derived from gastric juice protein, known for healing muscles, tendons, and digestive tract.",
    benefits: ["Muscle healing", "Tendon repair", "Gut repair", "Neuroprotection"],
    useCases: ["Injury research", "Tissue regeneration", "Wound healing studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 198, featured: "Great for tissue repair research." },
    purity: 99.9,
  },
  {
    id: "bpc157-10mg",
    name: "BPC 157 10mg",
    category: "Recovery & Healing",
    price: 87.00,
    subscriptionPrice: getSubscriptionPrice(87.00),
    image: "/images/precision-peptides-vial.png",
    overview: "BPC-157 is a synthetic peptide derived from gastric juice protein, known for healing muscles, tendons, and digestive tract.",
    benefits: ["Muscle healing", "Tendon repair", "Gut repair", "Neuroprotection"],
    useCases: ["Injury research", "Tissue regeneration", "Wound healing studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 234, featured: "Gold standard for tissue repair research." },
  },
  {
    id: "bpc157-20mg",
    name: "BPC 157 20mg",
    category: "Recovery & Healing",
    price: 133.00,
    subscriptionPrice: getSubscriptionPrice(133.00),
    image: "/images/precision-peptides-vial.png",
    overview: "BPC-157 is a synthetic peptide derived from gastric juice protein, known for healing muscles, tendons, and digestive tract.",
    benefits: ["Muscle healing", "Tendon repair", "Gut repair", "Neuroprotection"],
    useCases: ["Extended research", "Bulk studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 145, featured: "Great value for extended research." },
  },
  {
    id: "bpc10mg-tb10mg-combo",
    name: "BPC 10mg + TB 10mg (20mg)",
    category: "Recovery & Healing",
    price: 226.00,
    subscriptionPrice: getSubscriptionPrice(226.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Synergistic combination of BPC-157 and TB-500 for enhanced tissue repair research.",
    benefits: ["Synergistic healing", "Comprehensive repair", "Enhanced recovery"],
    useCases: ["Combination therapy research", "Enhanced healing studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.9, count: 156, featured: "Perfect combination for recovery research." },
  },
  {
    id: "tb500-5mg",
    name: "TB500 5mg",
    category: "Recovery & Healing",
    price: 96.00,
    subscriptionPrice: getSubscriptionPrice(96.00),
    image: "/images/precision-peptides-vial.png",
    overview: "TB-500 is a synthetic version of Thymosin Beta-4 that enhances tissue repair and reduces inflammation.",
    benefits: ["Muscle recovery", "Blood vessel growth", "Scar tissue reduction", "Flexibility"],
    useCases: ["Tissue repair research", "Wound healing research"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 189, featured: "Excellent for tissue repair research." },
  },
  {
    id: "tb500-10mg",
    name: "TB500 10mg",
    category: "Recovery & Healing",
    price: 175.00,
    subscriptionPrice: getSubscriptionPrice(175.00),
    image: "/images/precision-peptides-vial.png",
    overview: "TB-500 is a synthetic version of Thymosin Beta-4 that enhances tissue repair and reduces inflammation.",
    benefits: ["Muscle recovery", "Blood vessel growth", "Scar tissue reduction", "Flexibility"],
    useCases: ["Extended tissue repair research", "Bulk studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 134, featured: "Great value for extended research." },
  },
  {
    id: "thymosin-alpha-1-5mg",
    name: "Thymosin Alpha 1 5mg",
    category: "Recovery & Healing",
    price: 120.00,
    subscriptionPrice: getSubscriptionPrice(120.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Thymosin Alpha 1 modulates immune function and enhances T-cell production.",
    benefits: ["T-cell function", "Immune regulation", "Viral therapy support"],
    useCases: ["Immune research", "Recovery studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 68, featured: "Excellent for immune system research." },
  },
  {
    id: "thymosin-alpha-1-10mg",
    name: "Thymosin Alpha 1 10mg",
    category: "Recovery & Healing",
    price: 245.00,
    subscriptionPrice: getSubscriptionPrice(245.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Thymosin Alpha 1 modulates immune function and enhances T-cell production.",
    benefits: ["T-cell function", "Immune regulation", "Viral therapy support"],
    useCases: ["Extended immune research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 45, featured: "Premium immune research compound." },
  },
  {
    id: "ll37-2mg",
    name: "LL37 2mg",
    category: "Recovery & Healing",
    price: 46.00,
    subscriptionPrice: getSubscriptionPrice(46.00),
    image: "/images/precision-peptides-vial.png",
    overview: "LL-37 is an antimicrobial peptide with broad-spectrum activity against bacteria, viruses, and fungi.",
    benefits: ["Antimicrobial activity", "Wound healing", "Immune modulation"],
    useCases: ["Antimicrobial research", "Immune studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 56, featured: "Powerful antimicrobial peptide." },
  },
  {
    id: "ll37-5mg",
    name: "LL37 5mg",
    category: "Recovery & Healing",
    price: 126.00,
    subscriptionPrice: getSubscriptionPrice(126.00),
    image: "/images/precision-peptides-vial.png",
    overview: "LL-37 is an antimicrobial peptide with broad-spectrum activity against bacteria, viruses, and fungi.",
    benefits: ["Antimicrobial activity", "Wound healing", "Immune modulation"],
    useCases: ["Extended antimicrobial research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 38, featured: "Great value for antimicrobial research." },
  },
  {
    id: "kpv-5mg",
    name: "KPV 5mg",
    category: "Recovery & Healing",
    price: 55.00,
    subscriptionPrice: getSubscriptionPrice(55.00),
    image: "/images/precision-peptides-vial.png",
    overview: "KPV is a tripeptide with potent anti-inflammatory properties, particularly for gut inflammation.",
    benefits: ["Anti-inflammatory", "Gut health", "Immune modulation"],
    useCases: ["IBD research", "Anti-inflammatory studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 67, featured: "Excellent for gut inflammation research." },
  },
  {
    id: "kpv-10mg",
    name: "KPV 10mg",
    category: "Recovery & Healing",
    price: 73.00,
    subscriptionPrice: getSubscriptionPrice(73.00),
    image: "/images/precision-peptides-vial.png",
    overview: "KPV is a tripeptide with potent anti-inflammatory properties, particularly for gut inflammation.",
    benefits: ["Anti-inflammatory", "Gut health", "Immune modulation"],
    useCases: ["Extended IBD research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 45, featured: "Great value for extended research." },
  },
  {
    id: "vip-5mg",
    name: "VIP 5mg",
    category: "Recovery & Healing",
    price: 114.00,
    subscriptionPrice: getSubscriptionPrice(114.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Vasoactive Intestinal Peptide (VIP) has immunomodulatory and anti-inflammatory properties.",
    benefits: ["Immune modulation", "Anti-inflammatory", "Neuroprotection"],
    useCases: ["Immunology research", "CIRS studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 34, featured: "Important immunomodulatory peptide." },
  },
  {
    id: "vip-10mg",
    name: "VIP 10mg",
    category: "Recovery & Healing",
    price: 210.00,
    subscriptionPrice: getSubscriptionPrice(210.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Vasoactive Intestinal Peptide (VIP) has immunomodulatory and anti-inflammatory properties.",
    benefits: ["Immune modulation", "Anti-inflammatory", "Neuroprotection"],
    useCases: ["Extended immunology research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 23, featured: "Premium immunomodulatory research." },
  },
  {
    id: "ara290-10mg",
    name: "ARA290 (Cibinetide) 10mg",
    category: "Recovery & Healing",
    price: 120.00,
    subscriptionPrice: getSubscriptionPrice(120.00),
    image: "/images/precision-peptides-vial.png",
    overview: "ARA290 is an erythropoietin-derived peptide with tissue-protective and anti-inflammatory properties.",
    benefits: ["Tissue protection", "Anti-inflammatory", "Neuroprotection"],
    useCases: ["Neuropathy research", "Tissue protection studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 29, featured: "Promising neuroprotective compound." },
  },
  {
    id: "ara290-16mg",
    name: "ARA290 (Cibinetide) 16mg",
    category: "Recovery & Healing",
    price: 163.00,
    subscriptionPrice: getSubscriptionPrice(163.00),
    image: "/images/precision-peptides-vial.png",
    overview: "ARA290 is an erythropoietin-derived peptide with tissue-protective and anti-inflammatory properties.",
    benefits: ["Tissue protection", "Anti-inflammatory", "Neuroprotection"],
    useCases: ["Extended neuropathy research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 18, featured: "Great value for neuroprotection research." },
  },
  {
    id: "glutathione-600mg",
    name: "Glutathione 600mg",
    category: "Recovery & Healing",
    price: 60.00,
    subscriptionPrice: getSubscriptionPrice(60.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Glutathione is the master antioxidant, crucial for detoxification and cellular protection.",
    benefits: ["Antioxidant", "Detoxification", "Cellular protection"],
    useCases: ["Antioxidant research", "Detox studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 78, featured: "Essential antioxidant for research." },
  },
  {
    id: "glutathione-1500mg",
    name: "Glutathione 1500mg",
    category: "Recovery & Healing",
    price: 104.00,
    subscriptionPrice: getSubscriptionPrice(104.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Glutathione is the master antioxidant, crucial for detoxification and cellular protection.",
    benefits: ["Antioxidant", "Detoxification", "Cellular protection"],
    useCases: ["Extended antioxidant research", "High-dose studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 45, featured: "Great value for extended research." },
  },

  // ============================================
  // MUSCLE GROWTH CATEGORY
  // ============================================
  {
    id: "cjc1295-dac-5mg",
    name: "CJC1295 with DAC 5mg",
    category: "Muscle Growth",
    price: 226.00,
    subscriptionPrice: getSubscriptionPrice(226.00),
    image: "/images/precision-peptides-vial.png",
    overview: "CJC-1295 with DAC is a long-acting growth hormone-releasing hormone analog with extended half-life.",
    benefits: ["GH and IGF-1 increase", "Muscle growth", "Fat loss", "Recovery"],
    useCases: ["GH research", "Muscle development studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.9, count: 134, featured: "Excellent for extended research protocols." },
  },
  {
    id: "cjc1295-no-dac-5mg",
    name: "CJC 1295 (without DAC) 5mg",
    category: "Muscle Growth",
    price: 99.00,
    subscriptionPrice: getSubscriptionPrice(99.00),
    image: "/images/precision-peptides-vial.png",
    overview: "CJC-1295 without DAC has shorter duration and mimics natural GH pulses.",
    benefits: ["Natural GH release", "Muscle building", "Fat loss", "Recovery"],
    useCases: ["Short-term GH research", "Natural pulse studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 123, featured: "Excellent for short-acting GH research." },
  },
  {
    id: "cjc1295-ipamorelin-10mg",
    name: "CJC 1295 (without DAC) 5mg + IPA 5mg (10mg)",
    category: "Muscle Growth",
    price: 133.00,
    subscriptionPrice: getSubscriptionPrice(133.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Synergistic combination of CJC-1295 and Ipamorelin for enhanced GH release.",
    benefits: ["Synergistic GH release", "Muscle growth", "Fat loss", "Improved sleep"],
    useCases: ["Combination GH research", "Synergistic studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 167, featured: "Perfect combo for GH research." },
  },
  {
    id: "ipamorelin-5mg",
    name: "Ipamorelin 5mg",
    category: "Muscle Growth",
    price: 58.00,
    subscriptionPrice: getSubscriptionPrice(58.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Ipamorelin is a selective GH secretagogue known for stimulating GH without affecting cortisol.",
    benefits: ["Lean muscle growth", "Recovery enhancement", "Sleep improvement", "Fat metabolism"],
    useCases: ["GH research", "Muscle studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 203, featured: "Perfect for selective GH research." },
  },
  {
    id: "ipamorelin-10mg",
    name: "Ipamorelin 10mg",
    category: "Muscle Growth",
    price: 99.00,
    subscriptionPrice: getSubscriptionPrice(99.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Ipamorelin is a selective GH secretagogue known for stimulating GH without affecting cortisol.",
    benefits: ["Lean muscle growth", "Recovery enhancement", "Sleep improvement", "Fat metabolism"],
    useCases: ["Extended GH research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 145, featured: "Great value for extended research." },
  },
  {
    id: "sermorelin-5mg",
    name: "Sermorelin Acetate 5mg",
    category: "Muscle Growth",
    price: 95.00,
    subscriptionPrice: getSubscriptionPrice(95.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Sermorelin is a GHRH analog that stimulates natural growth hormone release.",
    benefits: ["Natural GH production", "Sleep quality", "Lean muscle", "Fat metabolism"],
    useCases: ["GH research", "Natural hormone studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 112, featured: "Great for natural GH research." },
  },
  {
    id: "sermorelin-10mg",
    name: "Sermorelin Acetate 10mg",
    category: "Muscle Growth",
    price: 152.00,
    subscriptionPrice: getSubscriptionPrice(152.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Sermorelin is a GHRH analog that stimulates natural growth hormone release.",
    benefits: ["Natural GH production", "Sleep quality", "Lean muscle", "Fat metabolism"],
    useCases: ["Extended GH research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 78, featured: "Great value for extended research." },
  },
  {
    id: "hexarelin-2mg",
    name: "Hexarelin Acetate 2mg",
    category: "Muscle Growth",
    price: 53.00,
    subscriptionPrice: getSubscriptionPrice(53.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Hexarelin is a potent GH secretagogue with cardiac protective properties.",
    benefits: ["GH release", "Cardiac protection", "Muscle growth"],
    useCases: ["GH research", "Cardiac studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 67, featured: "Potent GH secretagogue with cardiac benefits." },
  },
  {
    id: "hexarelin-5mg",
    name: "Hexarelin Acetate 5mg",
    category: "Muscle Growth",
    price: 113.00,
    subscriptionPrice: getSubscriptionPrice(113.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Hexarelin is a potent GH secretagogue with cardiac protective properties.",
    benefits: ["GH release", "Cardiac protection", "Muscle growth"],
    useCases: ["Extended GH research", "Advanced cardiac studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 45, featured: "Great value for extended research." },
  },
  {
    id: "ghrp-2-5mg",
    name: "GHRP-2 5mg",
    category: "Muscle Growth",
    price: 56.00,
    subscriptionPrice: getSubscriptionPrice(56.00),
    image: "/images/precision-peptides-vial.png",
    overview: "GHRP-2 stimulates the pituitary to secrete GH with appetite-stimulating effects.",
    benefits: ["GH levels increase", "Appetite enhancement", "Recovery improvement"],
    useCases: ["GH research", "Appetite studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 123, featured: "Reliable for GH research." },
  },
  {
    id: "ghrp-2-10mg",
    name: "GHRP-2 10mg",
    category: "Muscle Growth",
    price: 73.00,
    subscriptionPrice: getSubscriptionPrice(73.00),
    image: "/images/precision-peptides-vial.png",
    overview: "GHRP-2 stimulates the pituitary to secrete GH with appetite-stimulating effects.",
    benefits: ["GH levels increase", "Appetite enhancement", "Recovery improvement"],
    useCases: ["Extended GH research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 89, featured: "Great value for extended research." },
  },
  {
    id: "ghrp-2-15mg",
    name: "GHRP-2 15mg",
    category: "Muscle Growth",
    price: 98.00,
    subscriptionPrice: getSubscriptionPrice(98.00),
    image: "/images/precision-peptides-vial.png",
    overview: "GHRP-2 stimulates the pituitary to secrete GH with appetite-stimulating effects.",
    benefits: ["GH levels increase", "Appetite enhancement", "Recovery improvement"],
    useCases: ["Bulk GH research", "High-dose studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 56, featured: "Great for bulk research." },
  },
  {
    id: "ghrp-6-5mg",
    name: "GHRP-6 5mg",
    category: "Muscle Growth",
    price: 37.00,
    subscriptionPrice: getSubscriptionPrice(37.00),
    image: "/images/precision-peptides-vial.png",
    overview: "GHRP-6 strongly stimulates GH secretion and appetite for bulking support.",
    benefits: ["GH boost", "Muscle repair", "Appetite stimulation", "Fat loss"],
    useCases: ["GH research", "Appetite studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 134, featured: "Good for GH and appetite research." },
  },
  {
    id: "ghrp-6-10mg",
    name: "GHRP-6 10mg",
    category: "Muscle Growth",
    price: 60.00,
    subscriptionPrice: getSubscriptionPrice(60.00),
    image: "/images/precision-peptides-vial.png",
    overview: "GHRP-6 strongly stimulates GH secretion and appetite for bulking support.",
    benefits: ["GH boost", "Muscle repair", "Appetite stimulation", "Fat loss"],
    useCases: ["Extended GH research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 98, featured: "Great value for extended research." },
  },
  {
    id: "hcg-5000iu",
    name: "HCG 5000iu",
    category: "Muscle Growth",
    price: 106.00,
    subscriptionPrice: getSubscriptionPrice(106.00),
    image: "/images/precision-peptides-vial.png",
    overview: "HCG acts like LH, prompting testosterone production and supporting fertility.",
    benefits: ["Testosterone maintenance", "Testicular support", "Fertility"],
    useCases: ["Hormonal research", "Reproductive studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 145, featured: "Reliable for hormonal research." },
  },
  {
    id: "hcg-10000iu",
    name: "HCG 10000iu",
    category: "Muscle Growth",
    price: 199.00,
    subscriptionPrice: getSubscriptionPrice(199.00),
    image: "/images/precision-peptides-vial.png",
    overview: "HCG acts like LH, prompting testosterone production and supporting fertility.",
    benefits: ["Testosterone maintenance", "Testicular support", "Fertility"],
    useCases: ["Extended hormonal research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 89, featured: "Great value for extended research." },
  },
  {
    id: "tesamorelin-10mg",
    name: "Tesamorelin 10mg",
    category: "Muscle Growth",
    price: 247.00,
    subscriptionPrice: getSubscriptionPrice(247.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Tesamorelin is a GHRH analog that stimulates natural GH release, FDA-approved for HIV lipodystrophy.",
    benefits: ["Visceral fat reduction", "GH stimulation", "Body composition"],
    useCases: ["GHRH research", "Body composition studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 78, featured: "Excellent for body composition research." },
  },
  {
    id: "tesamorelin-20mg",
    name: "Tesamorelin 20mg",
    category: "Muscle Growth",
    price: 424.00,
    subscriptionPrice: getSubscriptionPrice(424.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Tesamorelin is a GHRH analog that stimulates natural GH release, FDA-approved for HIV lipodystrophy.",
    benefits: ["Visceral fat reduction", "GH stimulation", "Body composition"],
    useCases: ["Extended GHRH research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 45, featured: "Premium option for advanced research." },
  },
  {
    id: "igf1-lr3-1mg",
    name: "IGF-1 LR3 1mg",
    category: "Muscle Growth",
    price: 291.00,
    subscriptionPrice: getSubscriptionPrice(291.00),
    image: "/images/precision-peptides-vial.png",
    overview: "IGF-1 LR3 is a modified insulin-like growth factor with extended half-life for muscle growth research.",
    benefits: ["Muscle growth", "Cell proliferation", "Recovery enhancement"],
    useCases: ["IGF research", "Muscle development studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 67, featured: "Potent muscle growth research compound." },
  },
  {
    id: "fst344-1mg",
    name: "FST 344 1mg",
    category: "Muscle Growth",
    price: 364.00,
    subscriptionPrice: getSubscriptionPrice(364.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Follistatin 344 inhibits myostatin, potentially allowing for increased muscle growth.",
    benefits: ["Myostatin inhibition", "Muscle growth potential", "Strength support"],
    useCases: ["Myostatin research", "Muscle development studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 34, featured: "Cutting-edge myostatin research compound." },
  },

  // ============================================
  // LONGEVITY CATEGORY
  // ============================================
  {
    id: "epithalon-10mg",
    name: "Epithalon 10mg",
    category: "Longevity",
    price: 64.00,
    subscriptionPrice: getSubscriptionPrice(64.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Epithalon is a synthetic peptide that may extend telomere length and support longevity.",
    benefits: ["Telomere extension", "Anti-aging", "Sleep improvement", "Immune function"],
    useCases: ["Aging research", "Telomere studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 92, featured: "Exceptional quality for longevity research." },
  },
  {
    id: "epithalon-50mg",
    name: "Epithalon 50mg",
    category: "Longevity",
    price: 193.00,
    subscriptionPrice: getSubscriptionPrice(193.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Epithalon is a synthetic peptide that may extend telomere length and support longevity.",
    benefits: ["Telomere extension", "Anti-aging", "Sleep improvement", "Immune function"],
    useCases: ["Extended aging research", "Bulk studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.9, count: 56, featured: "Great value for extended research." },
  },
  {
    id: "mots-c-10mg",
    name: "MOTS-c (Human) 10mg",
    category: "Longevity",
    price: 90.00,
    subscriptionPrice: getSubscriptionPrice(90.00),
    image: "/images/precision-peptides-vial.png",
    overview: "MOTS-C is a mitochondrial-derived peptide involved in energy metabolism and longevity.",
    benefits: ["Insulin sensitivity", "Mitochondrial function", "Fat loss", "Longevity"],
    useCases: ["Mitochondrial research", "Metabolic studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 76, featured: "Excellent for mitochondrial research." },
  },
  {
    id: "mots-c-20mg",
    name: "MOTS-c (Human) 20mg",
    category: "Longevity",
    price: 183.00,
    subscriptionPrice: getSubscriptionPrice(183.00),
    image: "/images/precision-peptides-vial.png",
    overview: "MOTS-C is a mitochondrial-derived peptide involved in energy metabolism and longevity.",
    benefits: ["Insulin sensitivity", "Mitochondrial function", "Fat loss", "Longevity"],
    useCases: ["Extended mitochondrial research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 45, featured: "Great value for extended research." },
  },
  {
    id: "mots-c-40mg",
    name: "MOTS-c (Human) 40mg",
    category: "Longevity",
    price: 291.00,
    subscriptionPrice: getSubscriptionPrice(291.00),
    image: "/images/precision-peptides-vial.png",
    overview: "MOTS-C is a mitochondrial-derived peptide involved in energy metabolism and longevity.",
    benefits: ["Insulin sensitivity", "Mitochondrial function", "Fat loss", "Longevity"],
    useCases: ["Bulk mitochondrial research", "Institutional studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 28, featured: "Premium option for bulk research." },
  },
  {
    id: "nad-500mg",
    name: "NAD+ 500mg",
    category: "Longevity",
    price: 82.00,
    subscriptionPrice: getSubscriptionPrice(82.00),
    image: "/images/precision-peptides-vial.png",
    overview: "NAD+ is crucial for cellular energy metabolism, DNA repair, and healthy aging processes.",
    benefits: ["Cellular energy", "DNA repair", "Anti-aging", "Metabolic function"],
    useCases: ["Anti-aging research", "Cellular studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 89, featured: "Outstanding for anti-aging research." },
  },
  {
    id: "nad-1000mg",
    name: "NAD+ 1000mg",
    category: "Longevity",
    price: 99.00,
    subscriptionPrice: getSubscriptionPrice(99.00),
    image: "/images/precision-peptides-vial.png",
    overview: "NAD+ is crucial for cellular energy metabolism, DNA repair, and healthy aging processes.",
    benefits: ["Cellular energy", "DNA repair", "Anti-aging", "Metabolic function"],
    useCases: ["Extended anti-aging research", "High-dose studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.9, count: 67, featured: "Excellent value for extended research." },
  },
  {
    id: "ss31-10mg",
    name: "SS-31 10mg",
    category: "Longevity",
    price: 106.00,
    subscriptionPrice: getSubscriptionPrice(106.00),
    image: "/images/precision-peptides-vial.png",
    overview: "SS-31 (Elamipretide) targets mitochondria and may protect against age-related decline.",
    benefits: ["Mitochondrial protection", "Energy enhancement", "Anti-aging"],
    useCases: ["Mitochondrial research", "Aging studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 45, featured: "Promising mitochondrial-targeted peptide." },
  },
  {
    id: "ss31-50mg",
    name: "SS-31 50mg",
    category: "Longevity",
    price: 431.00,
    subscriptionPrice: getSubscriptionPrice(431.00),
    image: "/images/precision-peptides-vial.png",
    overview: "SS-31 (Elamipretide) targets mitochondria and may protect against age-related decline.",
    benefits: ["Mitochondrial protection", "Energy enhancement", "Anti-aging"],
    useCases: ["Extended mitochondrial research", "Bulk studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 23, featured: "Premium option for advanced research." },
  },
  {
    id: "cerebrolysin-60mg",
    name: "Cerebrolysin 60mg",
    category: "Longevity",
    price: 104.00,
    subscriptionPrice: getSubscriptionPrice(104.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Cerebrolysin is a brain-derived neurotrophic peptide preparation with neuroprotective properties.",
    benefits: ["Neuroprotection", "Cognitive support", "Brain health"],
    useCases: ["Neurological research", "Cognitive studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 56, featured: "Important neuroprotective compound." },
  },

  // ============================================
  // COGNITIVE CATEGORY
  // ============================================
  {
    id: "dihexa-oral-10mg-60pc",
    name: "Dihexa (Oral) 10mg x 60pc",
    category: "Cognitive",
    price: 81.00,
    subscriptionPrice: getSubscriptionPrice(81.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Dihexa is a potent cognitive enhancer that may promote synaptogenesis and neural repair.",
    benefits: ["Cognitive enhancement", "Synaptogenesis", "Neural repair"],
    useCases: ["Cognitive research", "Neurology studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 67, featured: "Powerful cognitive research compound." },
  },
  {
    id: "dihexa-oral-20mg-25pc",
    name: "Dihexa (Oral) 20mg x 25pc",
    category: "Cognitive",
    price: 240.00,
    subscriptionPrice: getSubscriptionPrice(240.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Dihexa is a potent cognitive enhancer that may promote synaptogenesis and neural repair.",
    benefits: ["Cognitive enhancement", "Synaptogenesis", "Neural repair"],
    useCases: ["Advanced cognitive research", "High-dose studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 34, featured: "Premium cognitive research option." },
  },
  {
    id: "dihexa-10mg",
    name: "Dihexa 10mg",
    category: "Cognitive",
    price: 120.00,
    subscriptionPrice: getSubscriptionPrice(120.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Injectable Dihexa for cognitive enhancement and neural repair research.",
    benefits: ["Cognitive enhancement", "Synaptogenesis", "Neural repair"],
    useCases: ["Injectable cognitive research", "Neurology studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 45, featured: "Injectable option for precise research." },
  },
  {
    id: "selank-5mg",
    name: "Selank 5mg",
    category: "Cognitive",
    price: 53.00,
    subscriptionPrice: getSubscriptionPrice(53.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Selank is a Russian-developed anxiolytic peptide with nootropic and immune-modulating properties.",
    benefits: ["Anxiety reduction", "Cognitive enhancement", "Immune support"],
    useCases: ["Anxiolytic research", "Nootropic studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 89, featured: "Excellent anxiolytic peptide." },
  },
  {
    id: "selank-10mg",
    name: "Selank 10mg",
    category: "Cognitive",
    price: 80.00,
    subscriptionPrice: getSubscriptionPrice(80.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Selank is a Russian-developed anxiolytic peptide with nootropic and immune-modulating properties.",
    benefits: ["Anxiety reduction", "Cognitive enhancement", "Immune support"],
    useCases: ["Extended anxiolytic research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 67, featured: "Great value for extended research." },
  },
  {
    id: "semax-5mg",
    name: "Semax 5mg",
    category: "Cognitive",
    price: 53.00,
    subscriptionPrice: getSubscriptionPrice(53.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Semax is a synthetic ACTH analog with neuroprotective and nootropic properties.",
    benefits: ["Cognitive enhancement", "Neuroprotection", "Focus improvement"],
    useCases: ["Nootropic research", "Neuroprotection studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 78, featured: "Reliable nootropic peptide." },
  },
  {
    id: "semax-10mg",
    name: "Semax 10mg",
    category: "Cognitive",
    price: 68.00,
    subscriptionPrice: getSubscriptionPrice(68.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Semax is a synthetic ACTH analog with neuroprotective and nootropic properties.",
    benefits: ["Cognitive enhancement", "Neuroprotection", "Focus improvement"],
    useCases: ["Extended nootropic research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 56, featured: "Great value for extended research." },
  },
  {
    id: "semax-30mg",
    name: "Semax 30mg",
    category: "Cognitive",
    price: 115.00,
    subscriptionPrice: getSubscriptionPrice(115.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Semax is a synthetic ACTH analog with neuroprotective and nootropic properties.",
    benefits: ["Cognitive enhancement", "Neuroprotection", "Focus improvement"],
    useCases: ["Bulk nootropic research", "Institutional studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.8, count: 34, featured: "Premium bulk option." },
  },
  {
    id: "dsip-5mg",
    name: "DSIP 5mg",
    category: "Cognitive",
    price: 60.00,
    subscriptionPrice: getSubscriptionPrice(60.00),
    image: "/images/precision-peptides-vial.png",
    overview: "DSIP (Delta Sleep Inducing Peptide) promotes deep sleep and hormone regulation.",
    benefits: ["Sleep quality", "Stress reduction", "Hormone regulation", "Recovery"],
    useCases: ["Sleep research", "Circadian studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 54, featured: "Great for sleep research." },
  },
  {
    id: "pe-22-28-5mg",
    name: "PE-22-28 5mg",
    category: "Cognitive",
    price: 113.00,
    subscriptionPrice: getSubscriptionPrice(113.00),
    image: "/images/precision-peptides-vial.png",
    overview: "PE-22-28 is a spadin analog that may have rapid antidepressant-like effects.",
    benefits: ["Mood support", "Rapid-acting", "Neuroplasticity"],
    useCases: ["Depression research", "Mood studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 28, featured: "Promising mood research compound." },
  },
  {
    id: "sr9009-oral-10mg",
    name: "SR9009 (Oral) 10mg",
    category: "Cognitive",
    price: 113.00,
    subscriptionPrice: getSubscriptionPrice(113.00),
    image: "/images/precision-peptides-vial.png",
    overview: "SR9009 is a Rev-ErbA agonist that may enhance metabolism, endurance, and circadian rhythm.",
    benefits: ["Metabolic enhancement", "Endurance support", "Circadian regulation"],
    useCases: ["Metabolic research", "Circadian studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 45, featured: "Interesting metabolic compound." },
  },
  {
    id: "slu-pp-322-5mg",
    name: "SLU-PP-322 5mg",
    category: "Cognitive",
    price: 171.00,
    subscriptionPrice: getSubscriptionPrice(171.00),
    image: "/images/precision-peptides-vial.png",
    overview: "SLU-PP-322 is an ERR agonist being studied for endurance and metabolic benefits.",
    benefits: ["Endurance enhancement", "Metabolic support", "Exercise mimetic"],
    useCases: ["Endurance research", "Metabolic studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.4, count: 23, featured: "Novel exercise mimetic compound." },
  },
  {
    id: "slu-pp-332-oral-250mcg",
    name: "SLU-PP-332 (oral) 250mcg x 100pcs",
    category: "Cognitive",
    price: 82.00,
    subscriptionPrice: getSubscriptionPrice(82.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Oral SLU-PP-332 for convenient endurance research applications.",
    benefits: ["Endurance enhancement", "Oral convenience", "Metabolic support"],
    useCases: ["Oral endurance research", "Convenient studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.4, count: 28, featured: "Convenient oral format." },
  },
  {
    id: "slu-pp-332-oral-500mcg",
    name: "SLU-PP-332 (Oral) 500mcg x 100pcs",
    category: "Cognitive",
    price: 90.00,
    subscriptionPrice: getSubscriptionPrice(90.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Oral SLU-PP-332 for convenient endurance research applications.",
    benefits: ["Endurance enhancement", "Oral convenience", "Metabolic support"],
    useCases: ["Higher dose oral research", "Extended studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 22, featured: "Good value mid-dose option." },
  },
  {
    id: "slu-pp-332-oral-1000mcg",
    name: "SLU-PP-332 (Oral) 1000mcg x 100pcs",
    category: "Cognitive",
    price: 98.00,
    subscriptionPrice: getSubscriptionPrice(98.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Oral SLU-PP-332 for convenient endurance research applications.",
    benefits: ["Endurance enhancement", "Oral convenience", "Metabolic support"],
    useCases: ["High dose oral research", "Bulk studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 18, featured: "Best value high-dose option." },
  },

  // ============================================
  // BIOREGULATORS CATEGORY
  // ============================================
  {
    id: "bronchogen-20mg",
    name: "Bronchogen 20mg",
    category: "Bioregulators",
    price: 202.00,
    subscriptionPrice: getSubscriptionPrice(202.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Bronchogen is a bioregulator peptide targeting bronchial and lung tissue health.",
    benefits: ["Respiratory support", "Lung tissue health", "Bioregulation"],
    useCases: ["Respiratory research", "Lung studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 23, featured: "Specialized respiratory bioregulator." },
  },
  {
    id: "cardiogen-10mg",
    name: "Cardiogen 10mg",
    category: "Bioregulators",
    price: 165.00,
    subscriptionPrice: getSubscriptionPrice(165.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Cardiogen is a bioregulator peptide supporting cardiovascular tissue health.",
    benefits: ["Cardiac support", "Cardiovascular health", "Bioregulation"],
    useCases: ["Cardiac research", "Cardiovascular studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 34, featured: "Important cardiac bioregulator." },
  },
  {
    id: "cardiogen-20mg",
    name: "Cardiogen 20mg",
    category: "Bioregulators",
    price: 203.00,
    subscriptionPrice: getSubscriptionPrice(203.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Cardiogen is a bioregulator peptide supporting cardiovascular tissue health.",
    benefits: ["Cardiac support", "Cardiovascular health", "Bioregulation"],
    useCases: ["Extended cardiac research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 23, featured: "Great value for extended research." },
  },
  {
    id: "cartalax-20mg",
    name: "Cartalax 20mg",
    category: "Bioregulators",
    price: 203.00,
    subscriptionPrice: getSubscriptionPrice(203.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Cartalax is a bioregulator peptide targeting cartilage and musculoskeletal tissue.",
    benefits: ["Cartilage support", "Joint health", "Musculoskeletal bioregulation"],
    useCases: ["Joint research", "Cartilage studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 28, featured: "Specialized joint bioregulator." },
  },
  {
    id: "chronluten-10mg",
    name: "Chronluten 10mg",
    category: "Bioregulators",
    price: 165.00,
    subscriptionPrice: getSubscriptionPrice(165.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Chronluten is a bioregulator peptide targeting respiratory system function.",
    benefits: ["Respiratory function", "Bronchial health", "Bioregulation"],
    useCases: ["Respiratory research", "Bronchial studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 19, featured: "Respiratory bioregulator peptide." },
  },
  {
    id: "cortagen-10mg",
    name: "Cortagen 10mg",
    category: "Bioregulators",
    price: 128.00,
    subscriptionPrice: getSubscriptionPrice(128.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Cortagen is a bioregulator peptide targeting adrenal cortex function.",
    benefits: ["Adrenal support", "Cortex regulation", "Stress response"],
    useCases: ["Adrenal research", "Stress studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 25, featured: "Adrenal bioregulator peptide." },
  },
  {
    id: "cortagen-20mg",
    name: "Cortagen 20mg",
    category: "Bioregulators",
    price: 203.00,
    subscriptionPrice: getSubscriptionPrice(203.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Cortagen is a bioregulator peptide targeting adrenal cortex function.",
    benefits: ["Adrenal support", "Cortex regulation", "Stress response"],
    useCases: ["Extended adrenal research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 18, featured: "Great value for extended research." },
  },
  {
    id: "ovagen-20mg",
    name: "Ovagen 20mg",
    category: "Bioregulators",
    price: 203.00,
    subscriptionPrice: getSubscriptionPrice(203.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Ovagen is a bioregulator peptide targeting liver and GI tract function.",
    benefits: ["Liver support", "GI health", "Hepatic bioregulation"],
    useCases: ["Liver research", "GI studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 22, featured: "Liver and GI bioregulator." },
  },
  {
    id: "pancragen-10mg",
    name: "Pancragen 10mg",
    category: "Bioregulators",
    price: 150.00,
    subscriptionPrice: getSubscriptionPrice(150.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Pancragen is a bioregulator peptide targeting pancreatic function.",
    benefits: ["Pancreatic support", "Digestive health", "Metabolic regulation"],
    useCases: ["Pancreatic research", "Metabolic studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 19, featured: "Pancreatic bioregulator peptide." },
  },
  {
    id: "prostamax-20mg",
    name: "Prostamax 20mg",
    category: "Bioregulators",
    price: 203.00,
    subscriptionPrice: getSubscriptionPrice(203.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Prostamax is a bioregulator peptide targeting prostate gland function.",
    benefits: ["Prostate support", "Urological health", "Glandular bioregulation"],
    useCases: ["Prostate research", "Urological studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 21, featured: "Prostate bioregulator peptide." },
  },
  {
    id: "pinealon-10mg",
    name: "Pinealon 10mg",
    category: "Bioregulators",
    price: 150.00,
    subscriptionPrice: getSubscriptionPrice(150.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Pinealon is a bioregulator peptide targeting pineal gland and brain function.",
    benefits: ["Pineal support", "Sleep regulation", "Neuroprotection"],
    useCases: ["Pineal research", "Sleep studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 34, featured: "Brain bioregulator peptide." },
  },
  {
    id: "pinealon-20mg",
    name: "Pinealon 20mg",
    category: "Bioregulators",
    price: 135.00,
    subscriptionPrice: getSubscriptionPrice(135.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Pinealon is a bioregulator peptide targeting pineal gland and brain function.",
    benefits: ["Pineal support", "Sleep regulation", "Neuroprotection"],
    useCases: ["Extended pineal research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 23, featured: "Great value for extended research." },
  },
  {
    id: "testagen-10mg",
    name: "Testagen 10mg",
    category: "Bioregulators",
    price: 150.00,
    subscriptionPrice: getSubscriptionPrice(150.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Testagen is a bioregulator peptide targeting testicular function.",
    benefits: ["Testicular support", "Hormone regulation", "Male reproductive health"],
    useCases: ["Testicular research", "Hormone studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 27, featured: "Male reproductive bioregulator." },
  },

  // ============================================
  // HORMONES & SEXUAL HEALTH CATEGORY
  // ============================================
  {
    id: "pt141-10mg",
    name: "PT141 10mg",
    category: "Hormones & Sexual Health",
    price: 87.00,
    subscriptionPrice: getSubscriptionPrice(87.00),
    image: "/images/precision-peptides-vial.png",
    overview: "PT-141 is a melanocortin receptor agonist that acts on the CNS to enhance sexual arousal.",
    benefits: ["Libido enhancement", "Sexual arousal", "CNS action"],
    useCases: ["Sexual health research", "Receptor studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.7, count: 76, featured: "Excellent for receptor binding studies." },
  },
  {
    id: "oxytocin-5mg",
    name: "Oxytocin Acetate 5mg",
    category: "Hormones & Sexual Health",
    price: 55.00,
    subscriptionPrice: getSubscriptionPrice(55.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Oxytocin is the \"bonding hormone\" involved in social behavior, trust, and reproduction.",
    benefits: ["Social bonding", "Trust enhancement", "Reproductive function"],
    useCases: ["Behavioral research", "Social studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 45, featured: "Important social behavior peptide." },
  },
  {
    id: "oxytocin-10mg",
    name: "Oxytocin Acetate 10mg",
    category: "Hormones & Sexual Health",
    price: 79.00,
    subscriptionPrice: getSubscriptionPrice(79.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Oxytocin is the \"bonding hormone\" involved in social behavior, trust, and reproduction.",
    benefits: ["Social bonding", "Trust enhancement", "Reproductive function"],
    useCases: ["Extended behavioral research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 34, featured: "Great value for extended research." },
  },
  {
    id: "kisspeptin-10-5mg",
    name: "Kisspeptin-10 5mg",
    category: "Hormones & Sexual Health",
    price: 73.00,
    subscriptionPrice: getSubscriptionPrice(73.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Kisspeptin plays a critical role in regulating reproductive hormones and puberty.",
    benefits: ["Hormone regulation", "Reproductive function", "GnRH stimulation"],
    useCases: ["Reproductive research", "Endocrine studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.5, count: 28, featured: "Important reproductive peptide." },
  },
  {
    id: "kisspeptin-10-10mg",
    name: "Kisspeptin-10 10mg",
    category: "Hormones & Sexual Health",
    price: 106.00,
    subscriptionPrice: getSubscriptionPrice(106.00),
    image: "/images/precision-peptides-vial.png",
    overview: "Kisspeptin plays a critical role in regulating reproductive hormones and puberty.",
    benefits: ["Hormone regulation", "Reproductive function", "GnRH stimulation"],
    useCases: ["Extended reproductive research", "Advanced studies"],
    disclaimer: "For research use only. Not for human consumption.",
    reviews: { rating: 4.6, count: 19, featured: "Great value for extended research." },
  },
]
